In [1]:
import numpy as np
from random import randint

In [2]:
def randomly_initialized_chessboard():
    '''
    output is a 8x8 nd.array representing the chess board
    1. 2 means rook 
    2. 1 means pawn 
    '''
    chess_board = np.zeros((8,8))
    
    while(1==1):
        rook_x = randint(0,7)
        rook_y = randint(0,7)
         
        pawn_x = randint(0,7)
        pawn_y = randint(0,7)
        
        if(rook_x != pawn_x and rook_y != pawn_x):
            break
        
    chess_board[rook_y][rook_x] = 2
    chess_board[pawn_y][pawn_x] = 1
    
    cache = {
            'rook_x':rook_x,
            'rook_y':rook_y,
            'pawn_x':pawn_x,
            'pawn_y':pawn_y
            }
    
    return chess_board, cache

In [3]:
for i in range(5):
    print('******************************')
    print(randomly_initialized_chessboard())
    

******************************
(array([[0., 0., 2., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), {'rook_x': 2, 'rook_y': 0, 'pawn_x': 6, 'pawn_y': 6})
******************************
(array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0., 0., 0.]]), {'rook_x': 2, 'rook_y': 7, 'pawn_x': 6, 'pawn_y': 4})
******************************
(array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0

In [4]:
def moves(chessboard_input,cache):
    '''assuming that the rook always moves first'''
    '''returns the final board positon and the number of moves'''
    chessboard = chessboard_input.copy()
    print('initial state:')
    print(chessboard)
    
    rook_x = cache['rook_x']
    rook_y = cache['rook_y']
         
    pawn_x = cache['pawn_x']
    pawn_y = cache['pawn_y']
    
    counter = 0
    while(1==1):
    
        if (np.sum(chessboard) == 3):
            if(rook_x == pawn_x or rook_y == pawn_y ):
                chessboard[rook_y][rook_x] = 0
                chessboard[pawn_y][pawn_x] = 2
                
                (rook_x,rook_y) = (pawn_x,pawn_y)
                counter = counter+1
                print('Move: '+ str(counter))
                print(chessboard)
                
            else:
                chessboard[rook_y][rook_x] = 0
                chessboard[rook_y][pawn_x] = 2
                
                (rook_x,rook_y) = (pawn_x,rook_y)
                
                if(pawn_y != (rook_y+1) and pawn_y != 0):
                    chessboard[pawn_y][pawn_x] = 0
                    chessboard[pawn_y-1][pawn_x] = 1
                    
                    pawn_y = pawn_y-1
                    counter = counter+1
                    print('Move: '+ str(counter))
                    print(chessboard)
                else:
                    counter = counter+1
                    print('Move: '+ str(counter))
                    print(chessboard)
                    
        if(np.sum(chessboard) < 3):
            print('Move: '+ str(counter))
            print('final')       
            break
    return chessboard,counter

In [5]:
for i in range(5):
    print('*************************')
    chessboard,cache = randomly_initialized_chessboard()
    moves(chessboard,cache)


*************************
initial state:
[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Move: 1
[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Move: 2
[[0. 0. 2. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Move: 2
final
*************************
initial state:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Move: 1
[[0. 1. 0. 0